Add account activation into account.
castcle/castcle-api pull request #1000
Opened 2022-03-28 06:29 UTC by nucastcle

2022-03-29 03:35 UTC, kittipong-castcle requested changes

2022-03-29 03:35 UTC, kittipong-castcle commented on libs/database/src/lib/models/account.model.ts
> +  type: 'email' | 'phone';
สร้าง enum

2022-03-29 03:35 UTC, kittipong-castcle commented on libs/database/src/lib/models/account.model.ts
> +export class AccountActivations {
```suggestion
export class AccountActivation {
```

2022-03-29 08:10 UTC, julapong-castcle approved these changes

2022-03-30 04:54 UTC, zong09 approved these changes

2022-03-30 05:31 UTC, merged