Add schema device into account and field devices.
castcle/castcle-api pull request #1005
Opened 2022-03-28 09:11 UTC by nucastcle

2022-03-29 03:35 UTC, PopCastcle approved these changes

2022-03-29 03:49 UTC, kittipong-castcle requested changes

2022-03-29 03:49 UTC, kittipong-castcle commented on libs/database/src/lib/models/account.model.ts
> +export class AccountDevices {
```suggestion
export class AccountDevice {
```

2022-03-29 03:49 UTC, kittipong-castcle commented on libs/database/src/lib/services/authentication.service.ts
> +      .exec();
รวมเป็น query เดียวกันเลยได้ไหม

2022-03-30 04:52 UTC, julapong-castcle approved these changes

2022-03-30 04:59 UTC, zong09 requested changes

2022-03-30 04:59 UTC, zong09 commented on libs/database/src/lib/services/authentication.service.ts
> +    const haveDevice = account?.devices
account?.devices มี validate ไปแล้วอันนีไม่น่าจะต้องเช็คอีกรึเปล่า

2022-03-30 06:57 UTC, zong09 approved these changes

2022-03-30 11:02 UTC, merged