Implement update user v.2
castcle/castcle-api pull request #1035
Opened 2022-04-04 09:56 UTC by nucastcle

2022-04-05 10:12 UTC, kittipong-castcle requested changes

2022-04-05 10:12 UTC, kittipong-castcle commented on apps/users/src/app/controllers/users.controller.v2.ts
> +  };
ดูของ syncSocial

2022-04-07 14:15 UTC, zong09 approved these changes

2022-04-08 11:45 UTC, kittipong-castcle requested changes

2022-04-08 11:45 UTC, kittipong-castcle commented on libs/database/src/lib/schemas/user.schema.ts
> +        (this as User).profile.images.avatar
Use optional chaining

2022-04-08 11:45 UTC, kittipong-castcle commented on libs/database/src/lib/services/user.service.v2.ts
> +export class UserServiceV2 {
อันไหนเหมือนเดิม ไม่ได้ปรับเลย ก็ไปใช้ของ v1 ดีกว่านะครับ

2022-04-11 04:47 UTC, merged