api castcles-id exist
castcle/castcle-api pull request #1077
Opened 2022-04-12 05:22 UTC by Nongeve

2022-04-12 05:54 UTC, kittipong-castcle requested changes

2022-04-12 05:54 UTC, kittipong-castcle commented on apps/authentications/src/app/controllers/authentications.controller.v2.ts
> +        exist: user ? true : false, // true=มีในระบบ, false=ไม่มีในระบบ
```suggestion
        exist: user ? true : false,
```
คอมเมนต์ไม่ต้องใส่มาครับ

2022-04-12 05:54 UTC, kittipong-castcle commented on libs/database/src/lib/services/authentication.service.v2.ts
> +  };
ลองหาดู มันมีฟังก์ชันประมาณนี้อยู่นะ จะได้ต้องทำขึ้นมาซ้ำๆ ครับ

2022-04-12 05:54 UTC, kittipong-castcle commented on libs/database/src/lib/services/authentication.service.v2.spec.ts
> +  describe('#getExistedUserFromCastcleId', () => {
ทำให้ครบทุกเคสครับ เช่น
1. user A exists -> find A -> return user A
2. user A deleted -> find A -> return null
3. user A exists -> find B -> return null

2022-04-12 08:50 UTC, Nongeve commented on apps/authentications/src/app/controllers/authentications.controller.v2.ts
> +        exist: user ? true : false, // true=มีในระบบ, false=ไม่มีในระบบ
already fixed

2022-04-12 08:50 UTC, Nongeve commented on libs/database/src/lib/services/authentication.service.v2.ts
> +  };
already fixed

2022-04-12 08:50 UTC, Nongeve commented on libs/database/src/lib/services/authentication.service.v2.spec.ts
> +  describe('#getExistedUserFromCastcleId', () => {
already fixed

2022-04-12 10:08 UTC, kittipong-castcle requested changes

2022-04-12 10:08 UTC, kittipong-castcle commented on libs/database/src/lib/services/authentication.service.v2.ts
> +    private authServiceV1: AuthenticationService
ไม่ได้ใช้ ?

```suggestion
```

2022-04-12 10:08 UTC, kittipong-castcle commented on libs/database/src/lib/services/authentication.service.spec.ts
> +        const castcleId = 'dudethisisnew';
https://marketplace.visualstudio.com/items?itemName=streetsidesoftware.code-spell-checker

ลองใช้ดูครับ ถ้ามันสีน้ำเงินก็ควรแก้นะ 555

2022-04-12 10:09 UTC, kittipong-castcle requested changes

2022-04-12 10:09 UTC, kittipong-castcle commented on apps/authentications/src/app/controllers/authentications.controller.v2.ts
> +  @Post('exists/castcle-id')
อันนี้ได้เทสยิง API จริงหรือยังที่ ดูเหมือนมันจะไม่ map field นี้มานะครับ

2022-04-19 06:51 UTC, kittipong-castcle requested changes

2022-04-19 06:51 UTC, kittipong-castcle commented on apps/authentications/src/app/controllers/authentications.controller.v2.ts
> +    }
```suggestion
    return this.authenticationService.checkUserExist(body.castcleId);
```

มี exception filter อยู่แล้วนะ ไม่จำเป็นต้อง try catch ครอบส่วน controller ก็ได้ครับ

2022-04-19 06:51 UTC, kittipong-castcle commented on libs/database/src/lib/dtos/response.dto.ts
> +}
message เห็นว่าไม่ได้ใช้ ตัดออกไหมครับ ถ้าออกได้มันจะไปคล้ายตัว ResponseDto ซึ่งเป็น generic type รองรับไว้อยู่แล้ว ดังนั้นก็สร้างแค่ตัว payload type ก็พอ แล้วเรียกใช้แบบนี้แทน เช่น ResponseDto.ok<CheckingPayload>(true|false) อะไรแบบนี้

2022-04-19 06:51 UTC, kittipong-castcle commented on libs/database/src/lib/services/authentication.service.v2.ts
> +    const user = await this.getExistedUserFromCastcleId(castcleId);
ตัว service ควร return type ที่สามารถนำไปใช้ต่อได้เลย เช่น User, boolean, Account, number อะไรแบบนี้ แล้วค่อยไปจัด response ที่ controller ครับ

2022-04-19 08:51 UTC, julapong-castcle commented on apps/authentications/src/app/controllers/authentications.controller.v2.ts
> +    }
+1

2022-04-19 08:52 UTC, julapong-castcle commented on libs/database/src/lib/dtos/response.dto.ts
> +}
+1

2022-04-19 08:52 UTC, julapong-castcle commented on libs/database/src/lib/services/authentication.service.v2.ts
> +    const user = await this.getExistedUserFromCastcleId(castcleId);
+1

2022-04-19 15:11 UTC, julapong-castcle approved these changes

2022-04-20 13:09 UTC, nucastcle commented on libs/database/src/lib/services/authentication.service.spec.ts
> +        expect(findUser.visibility).toEqual(EntityVisibility.Deleted);
expected result ตรงนี้แนะนำให้ทำชัดเจนกว่านี้ได้ไหมครับ เช่น 'should return null after delete user' findUser จะต้องเป็น null หลังจาก delete user

2022-04-20 13:09 UTC, nucastcle commented on libs/database/src/lib/services/authentication.service.v2.spec.ts
> +      expect(findUser.visibility).toEqual(EntityVisibility.Deleted);
ตรงนี้ด้วยครับ

2022-04-21 10:23 UTC, kittipong-castcle approved these changes

2022-04-22 05:20 UTC, PopCastcle approved these changes

2022-04-22 06:52 UTC, merged