feature/email-exist
castcle/castcle-api pull request #1079
Opened 2022-04-12 05:38 UTC by Nongeve

2022-04-12 06:00 UTC, kittipong-castcle requested changes

2022-04-12 06:00 UTC, kittipong-castcle commented on libs/database/src/lib/services/authentication.service.v2.ts
> +  };
```suggestion
```

ใช้ @IsEmail ของ class-validator

2022-04-12 06:00 UTC, kittipong-castcle commented on apps/authentications/src/app/controllers/authentications.controller.v2.ts
> +    try {
ดูจาก getAccountFromEmail แล้ว ไม่น่าจะมี throw อะไรออกมานะครับ ดังนั้น try catch มันไม่จำเป็นนะครับ

2022-04-12 06:00 UTC, kittipong-castcle commented on apps/authentications/src/app/controllers/authentications.controller.v2.ts
> +      throw CastcleException.INVALID_EMAIL;
```suggestion
```
ใน dto มี validation อยู่แล้วนะครับ ลองดูเทสก่อนว่าเวิคไหม ถ้าเวิค ส่วนนี้ก็ไม่จำเป็นครับ

2022-04-19 15:11 UTC, julapong-castcle approved these changes

2022-04-20 13:01 UTC, nucastcle commented on apps/authentications/src/app/controllers/authentications.controller.v2.ts
> +    @Req() req: HeadersRequest,
```suggestion
    @Req() req: HeadersRequest,
```
ตรงนี้ได้ใช้ไหมครับถ้าไม่ได้ใช้ก็ ไม่จำเป็นต้องเรียก

2022-04-20 13:06 UTC, nucastcle commented on libs/database/src/lib/services/authentication.service.v2.ts
> +    @InjectModel('Account') public accountModel: Model<Account>,
```suggestion
    @InjectModel('Account') private accountModel: Model<Account>,
```
ตรงนี้แนะนำให้ใช้เป็น private ดีกว่าไหมครับ ในส่วน unit test ให้ใช้ (service as any).xxx แบบนี้แทน

2022-04-21 10:24 UTC, kittipong-castcle approved these changes

2022-04-22 05:20 UTC, PopCastcle approved these changes

2022-04-22 07:33 UTC, merged