Feature/refreshtoken
castcle/castcle-api pull request #1093
Opened 2022-04-18 05:30 UTC by Nongeve

2022-04-22 03:04 UTC, PopCastcle commented on apps/authentications/src/app/controllers/authentications.controller.v2.ts
> +     */
ไม่ต้องทำแล้วเอา todo ออก เลยครับ

2022-04-22 03:09 UTC, PopCastcle requested changes
delete some unused comment / double check service injection

2022-04-22 03:09 UTC, PopCastcle commented on libs/database/src/lib/services/authentication.service.v2.ts
> +    private userService: UserService
ถ้า UserService ใช้ V2 จะกลายเป็น
userService ต้อง inject authenService(V2) แล้ว authenService(V2) เรียกใช้ userService รึป่าวครับ

2022-04-22 09:29 UTC, nucastcle commented on libs/database/src/lib/services/authentication.service.v2.ts
> +    const result = this.generateAccessToken(payload);
ระบุชื่อ variable ให้สื่อความหมาย ไม่ควรใช้ result or data
```suggestion
    const newAccessToken = this.generateAccessToken(payload);
```

2022-04-22 09:32 UTC, nucastcle commented on libs/database/src/lib/services/authentication.service.v2.ts
> +      console.debug('mainUser', user);
ตรงนี้ ถ้าต้องการ debug แนะนำใช้ CastLogger ที่ import มาด้านบน ดีไหมครับ

2022-04-22 09:33 UTC, nucastcle commented on libs/database/src/lib/services/authentication.service.v2.ts
> +      console.debug('payload', payload);
ตรงนี้ ถ้าต้องการ debug แนะนำใช้ CastLogger ที่ import มาด้านบน ดีไหมครับ

2022-04-26 10:39 UTC, julapong-castcle approved these changes

2022-04-27 03:51 UTC, kittipong-castcle requested changes

2022-04-27 03:51 UTC, kittipong-castcle commented on libs/database/src/lib/services/authentication.service.v2.ts
> +
เขียนแบบ early return (guard clauses) + optional chaining ครับ

```suggestion
  async getRefreshToken(refreshToken: string) {
    const credential = await this.repository.findCredential({ refreshToken });
    if (!credential?.isRefreshTokenValid()) throw CastcleException.INVALID_REFRESH_TOKEN;
    const account = await this.repository.findAccount({
      _id: credential.account._id,
    });
    return this.login(credential, account);
  }
```

2022-04-27 08:01 UTC, kittipong-castcle approved these changes

2022-04-28 06:56 UTC, merged