Feature/my pages
castcle/castcle-api pull request #1115
Opened 2022-04-21 09:49 UTC by Nongeve

2022-04-22 09:56 UTC, PopCastcle requested changes

2022-04-22 09:56 UTC, PopCastcle commented on apps/users/src/app/controllers/users.controller.v2.ts
> +  async getMyPages(@Req() { $credential }: CredentialRequest) {
ใช้ authorizer ครับ

2022-04-25 03:50 UTC, nucastcle approved these changes

2022-04-25 09:28 UTC, julapong-castcle approved these changes

2022-04-25 09:59 UTC, PopCastcle approved these changes

2022-04-25 10:33 UTC, merged