Feature/block user
castcle/castcle-api pull request #1156
Opened 2022-04-27 06:32 UTC by Nongeve

2022-04-28 07:50 UTC, julapong-castcle approved these changes

2022-04-29 04:09 UTC, nucastcle approved these changes

2022-05-03 06:06 UTC, PopCastcle approved these changes

2022-05-03 09:00 UTC, kittipong-castcle requested changes

2022-05-03 09:00 UTC, kittipong-castcle commented on libs/database/src/lib/services/user.service.v2.ts
> +        { upsert: true }
```suggestion
        { upsert: true, session }
```
ฝากดูเรื่อง mongoose session เพิ่มหน่อยครับ

2022-05-03 09:00 UTC, kittipong-castcle commented on libs/database/src/lib/services/user.service.v2.ts
> +      meta: Meta.fromDocuments(users, total),
ฝากเช็ค API response หน่อยครับ บางตัวไม่ได้ใช้ ก็เอาออกเลย

2022-05-03 09:00 UTC, kittipong-castcle commented on libs/database/src/lib/services/user.service.v2.ts
> +    const filterQuery = { ...query };
`filterQuery === query` ทำไมต้อง clone มาใช้ ใช้ query แทนเลยได้ไหม

2022-05-05 06:21 UTC, kittipong-castcle approved these changes

2022-05-05 06:21 UTC, kittipong-castcle commented on libs/database/src/lib/services/user.service.v2.ts
> +    if (!blockUser || !targetCastcleId)
```suggestion
    if (!blockUser)
```

targetCastcleId ถูก validate จาก controller แล้วว่าต้อง IsString + IsNotEmpty ซึ่งมันไม่โอกาศเป็น falsy value แล้วนะ ผมว่าตรงนี้ไม่จำเป็น

2022-05-05 07:31 UTC, merged