api block user lookup
castcle/castcle-api pull request #1174
Opened 2022-04-28 06:38 UTC by Nongeve

remove unused function

api block-lookup

2022-04-28 07:50 UTC, julapong-castcle approved these changes

2022-04-29 03:47 UTC, nucastcle commented on libs/database/src/lib/services/user.service.v2.ts
> +    query: FilterQuery<User>,
```suggestion
  getAllByCriteria = async (
    query: FilterQuery<User>,
```
ตรงนี้ ส่ง { _id : userId } แนะนำให้ ใช้ class มารับดีกว่าครับ FilterQuery จะต้องไม่ ประกาศ any และ ลดการซ้ำซ้อน สุดท้ายฝั่ง  query: FilterQuery<User> ก็ไป prepare filterQuery อยู่ดี

2022-04-29 03:57 UTC, nucastcle commented on libs/database/src/lib/services/user.service.v2.ts
> +    }
```suggestion
    if (queryOptions?.limit) usersQuery = usersQuery.limit(queryOptions.limit);
    if (queryOptions?.page) usersQuery = usersQuery.skip(queryOptions.page - 1);
    if (queryOptions?.sortBy) {
      const sortDirection = queryOptions.sortBy.type === 'desc' ? '-' : '';
      const sortOrder = `${sortDirection}${queryOptions.sortBy.field}`;
      usersQuery = usersQuery.sort(sortOrder);
    }
```
ตรงนี้ ไม่แน่ใจว่ามีค่า default อยู่แล้วหรือป่าวครับ ถ้ามีแล้วไม่ต้อง check ก็ได้ครับ

2022-04-29 04:06 UTC, nucastcle commented on libs/database/src/lib/services/user.service.v2.ts
> +    let usersQuery = this.repositoryService.findUsers(filterQuery as any);
```suggestion
    let usersQuery = this.repositoryService.findUsers(filterQuery, {$limit: queryOptions.limit, $skip: queryOptions.page - 1, $sort: { [queryOptions.sortBy.field] : queryOptions.sortBy.type === SortDirection.DESC ? -1 : 1 } });
```

2022-05-03 06:06 UTC, PopCastcle approved these changes

2022-05-05 12:43 UTC, nucastcle approved these changes

2022-05-06 03:43 UTC, kittipong-castcle requested changes

2022-05-06 03:43 UTC, kittipong-castcle commented on libs/database/src/lib/services/user.service.v2.ts
> +    );
`Array<ObjectId>` --> `Array<String>` --> `Array<ObjectId>` ???

2022-05-06 07:01 UTC, kittipong-castcle requested changes

2022-05-06 07:01 UTC, kittipong-castcle commented on libs/database/src/lib/services/user.service.v2.ts
> +    );
```suggestion
    const userIds = relationships.map(({ followedUser }) => followedUser);
```

followedUser ที่เก็บไว้ใน relationship เป็น ObjectId อยู่แล้ว

2022-05-06 07:26 UTC, kittipong-castcle approved these changes

2022-05-06 07:56 UTC, merged