feature/unblock
castcle/castcle-api pull request #1176
Opened 2022-04-28 06:43 UTC by Nongeve

unblock api

2022-04-28 07:51 UTC, julapong-castcle approved these changes

2022-04-29 05:37 UTC, PopCastcle commented on libs/database/src/lib/services/user.service.v2.ts
> +  async blockUser(user: User, targetCastcleId: string) {
please add unit test

2022-04-29 05:37 UTC, PopCastcle requested changes
add unit test / withTransaction

2022-04-29 05:37 UTC, PopCastcle commented on libs/database/src/lib/services/user.service.v2.ts
> +      ),
please use session / withTransaction()

2022-05-03 06:07 UTC, PopCastcle approved these changes

2022-05-05 10:44 UTC, merged