refractor unblock api
castcle/castcle-api pull request #1199
Opened 2022-05-06 08:01 UTC by Nongeve

2022-05-07 09:15 UTC, nucastcle commented on libs/database/src/lib/repositories/index.ts
> +  findContentById(contentId: string) {
ใช้ findContent() ดีกว่าไหมครับ

2022-05-07 09:19 UTC, nucastcle commented on libs/database/src/lib/services/user.service.v2.spec.ts
> +      expect(blockedUser).toEqual([]);
```suggestion
      expect(blockerUser).toHaveLength(0);
      expect(blockedUser).toHaveLength(0);
```

2022-05-10 05:32 UTC, kittipong-castcle requested changes

2022-05-10 05:32 UTC, kittipong-castcle commented on libs/database/src/lib/services/user.service.v2.ts
> +      const [blockerRelation, blockedRelation] = await Promise.all([
relationship ถ้าจะลบ ควรลบเมื่อ ไม่มีการ block และ follow นะ เช่น กรณีที่เจอ feed จากที่ไม่ได้ follow แล้วกด block ไม่อยากให้เห็นของคนนี้ ควรจะเกิด `following: false, blocking: true` เพื่อเอาไป filter ออกจาก feed ครั้งหน้านะครับ คหสต.

2022-05-12 05:15 UTC, kittipong-castcle approved these changes

2022-05-12 09:17 UTC, julapong-castcle approved these changes

2022-05-12 09:18 UTC, nucastcle approved these changes

2022-05-12 09:32 UTC, merged