Feature/guest login
castcle/castcle-api pull request #1200
Opened 2022-05-06 08:33 UTC by Nongeve

2022-05-07 09:28 UTC, nucastcle commented on libs/database/src/lib/services/authentication.service.v2.ts
> +          role: 'guest',
แนะนำให้ใช้ enum AccountRole

2022-05-12 09:19 UTC, nucastcle commented on libs/database/src/lib/repositories/index.ts
> +    @InjectModel('Credential') private credentialModel: CredentialModel,
??

2022-05-12 11:39 UTC, Nongeve commented on libs/database/src/lib/repositories/index.ts
> +    @InjectModel('Credential') private credentialModel: CredentialModel,
จะใช้ฟังชั่น generate token อ่ะครับ

2022-05-18 04:59 UTC, kittipong-castcle requested changes

2022-05-18 04:59 UTC, kittipong-castcle commented on libs/database/src/lib/services/authentication.service.v2.ts
> +    @InjectModel('Account') private accountModel: Model<Account>,
ย้ายไปอยู่ใน repo

2022-05-18 04:59 UTC, kittipong-castcle commented on libs/database/src/lib/services/authentication.service.v2.ts
> +            _id: Types.ObjectId(account._id),
._id = ObjectId อยู่แล้ว

2022-05-18 04:59 UTC, kittipong-castcle commented on libs/database/src/lib/services/authentication.service.v2.ts
> +          id: account._id as string,
ถ้าจะเปลี่ยนเป็น String ควรใช้ String(account._id)

2022-05-18 04:59 UTC, kittipong-castcle commented on libs/database/src/lib/services/authentication.service.v2.ts
> +          id: account._id as string,
ถ้าจะเปลี่ยนเป็น String ควรใช้ String(account._id)

2022-05-18 04:59 UTC, kittipong-castcle commented on libs/database/src/lib/services/authentication.service.v2.ts
> +      throw CastcleException.FORBIDDEN;
forbidden ใช้สำหรับเรื่อง permission นะครับ กรณีนี้ควรเป็นพวก server error หรือ unprocessable entity มากกว่า

2022-05-18 07:31 UTC, kittipong-castcle approved these changes

2022-05-18 08:09 UTC, julapong-castcle approved these changes

2022-05-18 09:02 UTC, merged