Feature/suggestion follow
castcle/castcle-api pull request #1248
Opened 2022-05-23 07:48 UTC by Nongeve

2022-05-24 10:06 UTC, kittipong-castcle requested changes

2022-05-24 10:06 UTC, kittipong-castcle commented on apps/users/src/app/services/suggestion.service.v2.ts
> +        this._suggestKey(authorizer.credential.accessToken),
```suggestion
        CacheKey.ofSuggesUser(authorizer.credential.accessToken),
```
Should create a new class for storing all cache key patterns

2022-05-26 07:30 UTC, kittipong-castcle requested changes

2022-05-26 07:30 UTC, kittipong-castcle commented on libs/database/src/lib/services/suggestion.service.v2.ts
> +  private async querySuggestByDataScience(account: Account, accessKey: string) {
```suggestion
  private async querySuggestByDataScience(accountId: String, accessKey: string) {
```

2022-05-26 07:30 UTC, kittipong-castcle commented on libs/environments/src/index.ts
> +export * from './lib/cache-key';
sort ตามชื่อไฟล์ด้วย ถ้ามันเยอะ เดี๋ยวมันจะซ้ำ

2022-05-26 07:30 UTC, kittipong-castcle commented on libs/database/src/lib/services/suggestion.service.v2.ts
> +    account: Account,
```suggestion
```
ถ้าใช้แค่ id ใช้ user.ownerAccount

2022-05-26 07:30 UTC, kittipong-castcle commented on libs/database/src/lib/services/suggestion.service.v2.ts
> +    let sliceUsers: User[] = [];
ถ้าเช็คจาก sinceId หรือ untilId มันมีโอกาศที่ cache หมดอายุแล้ว error ไปก่อนนะ

ผมว่าควรเป็นแบบนี้
If `มี UsersFromCache && (sinceId, untilId) isSubset UsersFromCache`
    -> `return UsersFromCache[sinceId,untilId]`
else
    -> `return users from data service`

2022-06-01 06:57 UTC, kittipong-castcle requested changes

2022-06-01 06:57 UTC, kittipong-castcle commented on libs/database/src/lib/services/suggestion.service.v2.ts
> +        (user) => user._id === pageQuery.sinceId,
_id => type: ObjectId
sinceId => type: String

`_id !== sinceId`

2022-06-06 04:18 UTC, julapong-castcle approved these changes

2022-06-06 04:18 UTC, merged