Feature/followers
castcle/castcle-api pull request #1249
Opened 2022-05-23 09:56 UTC by Nongeve

api followers v2

2022-05-24 02:58 UTC, PopCastcle approved these changes

2022-05-24 09:36 UTC, kittipong-castcle requested changes

2022-05-24 09:36 UTC, kittipong-castcle commented on apps/users/src/app/controllers/users.controller.ts
> -
Adding a new line may improve the readability.
- before/after `if`
- after multiline declaration `const`/`let`
- before/after `import`

2022-05-24 09:36 UTC, kittipong-castcle commented on libs/database/src/lib/aggregations/get-users-relation.aggregation.ts
> +    ],
```suggestion
    { $count: 'total' },
```

2022-05-24 09:36 UTC, kittipong-castcle commented on libs/database/src/lib/aggregations/get-users-relation.aggregation.ts
> +const filterTypeV2 = (userType?: string[]) => {
```suggestion
const filterTypes = (userTypes?: string[]) => {
```

2022-05-24 09:36 UTC, kittipong-castcle commented on libs/database/src/lib/services/user.service.v2.ts
>  @Injectable()
```suggestion
import { UserService } from './user.service';

@Injectable()
```

2022-05-24 09:48 UTC, kittipong-castcle requested changes

2022-05-24 09:48 UTC, kittipong-castcle commented on libs/database/src/lib/aggregations/get-users-relation.aggregation.ts
> +        as: 'user_relation',
```suggestion
        as: 'user',
```
Replace it with `user`, not necessary to create new property

2022-05-24 10:15 UTC, kittipong-castcle requested changes

2022-05-24 10:15 UTC, kittipong-castcle commented on libs/database/src/lib/aggregations/get-users-relation.aggregation.ts
> +      'user_relation.type': { $in: userTypes },
```suggestion
      'user.type': { $in: userTypes },
```

2022-05-24 10:15 UTC, kittipong-castcle commented on libs/database/src/lib/services/user.service.v2.ts
> +      hasRelationship,
```suggestion
      followQuery.hasRelationshipExpansion,
```

2022-05-24 10:15 UTC, kittipong-castcle commented on libs/database/src/lib/services/user.service.v2.ts
> +    );
```suggestion
    const followingUsersId = userRelation.flatMap(({_id, user}) => {
        return {
          userId: user[0]?._id,
          relationshipId: _id,
        };
      }),
    );
```

2022-05-26 07:36 UTC, kittipong-castcle requested changes

2022-05-26 07:36 UTC, kittipong-castcle commented on libs/database/src/lib/aggregations/get-users-relation.aggregation.ts
> +export type GetUserRelationResponseV2 = Relationship & {
ใช้ mongoose $project (aggregate) แทนที่ค่า user ด้วย user[0] จะได้ไม่ต้องสร้าง type ใหม่

2022-05-31 03:52 UTC, kittipong-castcle approved these changes

2022-05-31 03:53 UTC, merged