Feature/content farming calculation
castcle/castcle-api pull request #1271
Opened 2022-05-26 13:56 UTC by PopCastcle

2022-05-27 09:28 UTC, kittipong-castcle requested changes

2022-05-27 09:28 UTC, kittipong-castcle commented on apps/queues/src/app/social-reward.sheduler.ts
> +    //check if there is queue command to distribute reward
```suggestion
```

2022-05-27 09:28 UTC, kittipong-castcle commented on apps/queues/src/app/social-reward.sheduler.ts
> +    if (actionQueue) {
```suggestion
    if (actionQueue) return;
```

2022-05-27 09:28 UTC, kittipong-castcle commented on libs/database/src/lib/services/ads.service.ts
> +    console.log('filter');
```suggestion
```

2022-05-27 09:28 UTC, kittipong-castcle commented on libs/database/src/lib/services/content.service.v2.ts
> +import cdf from 'castcle-cdf';
```suggestion
import cdf from 'castcle-cdf';
```

2022-05-27 09:28 UTC, kittipong-castcle commented on libs/database/src/lib/services/content.service.v2.ts
> +    //const prospectContentFarmings = await this.contentFarmingModel.find({isDistributed: {$ne:true}},{ }, {sort: 'startAt:1'} );
```suggestion
```

2022-05-27 09:28 UTC, kittipong-castcle commented on libs/database/src/lib/services/ads.service.ts
> +    //transfer rewardContent from ads credit lock to cfs[0].account;
```suggestion
```

2022-05-27 09:28 UTC, kittipong-castcle commented on libs/database/src/lib/services/ads.service.ts
> +    //!!! TODO should embed in adsplacement
```suggestion
```

2022-05-27 09:28 UTC, kittipong-castcle commented on libs/database/src/lib/services/ads.service.ts
> +        //has content farming
```suggestion
```

2022-05-27 09:28 UTC, kittipong-castcle commented on libs/database/src/lib/services/ads.service.ts
> +        const ledgers: any[] = [];
```suggestion
        const transferTo: type?[] = [];
        const ledgers: type?[] = [];
```

2022-05-27 09:28 UTC, kittipong-castcle commented on libs/database/src/lib/services/ads.service.ts
> +    const ledgers: any[] = [];
```suggestion
    const transferTo: type?[] = [];
    const ledgers: type?[] = [];
```

2022-05-27 09:28 UTC, kittipong-castcle commented on libs/database/src/lib/services/ads.service.ts
> +    //distribute Content Farming
```suggestion
```

2022-05-27 09:28 UTC, kittipong-castcle commented on libs/database/src/lib/services/ads.service.ts
> +    //gety cost UST in aggregation
```suggestion
```

2022-05-27 09:28 UTC, kittipong-castcle commented on libs/database/src/lib/services/ads.service.ts
> +    //assume all conterm farming has been weigh
```suggestion
```

2022-05-27 09:28 UTC, kittipong-castcle commented on libs/database/src/lib/services/ads.service.ts
> +    //gety cost UST in aggregation
```suggestion
```

2022-05-27 09:28 UTC, kittipong-castcle commented on libs/database/src/lib/services/ads.service.ts
> +    //have permission to add payment
```suggestion
```

2022-05-27 09:28 UTC, kittipong-castcle commented on libs/database/src/lib/services/ads.service.ts
> +    if (adsRequest.userId && user.id !== adsRequest.userId) {
```suggestion
    if (user.id !== adsRequest.userId) {
```

2022-05-27 09:28 UTC, kittipong-castcle commented on libs/database/src/lib/schemas/ads-placement.schema.ts
> +  contents: AdsPlacementContent[]; // array ob objectId
```suggestion
  @Prop({ required: true, type: [SchemaTypes.ObjectId] })
  contents: AdsPlacementContent[];
```

2022-05-27 09:28 UTC, kittipong-castcle commented on libs/database/src/lib/schemas/ads-campaign.schema.ts
> +import { User, CastcleBase } from '.';
```suggestion
import { CastcleBase } from './common.ts';
import { User } from './user.ts';
```

circular
user -> index -> ads

2022-05-27 09:45 UTC, PopCastcle commented on libs/database/src/lib/schemas/ads-placement.schema.ts
> +  contents: AdsPlacementContent[]; // array ob objectId
type is not object id

2022-05-29 12:56 UTC, nucastcle approved these changes

2022-05-30 04:44 UTC, kittipong-castcle requested changes

2022-05-30 04:44 UTC, kittipong-castcle commented on apps/queues/src/app/social-reward.sheduler.ts
> +    actionQueue.save();
```suggestion
    await actionQueue.save();
```

2022-05-30 04:44 UTC, kittipong-castcle commented on libs/database/src/lib/services/content.service.v2.ts
> +    return result;
```suggestion
    return contents.map<ContentFarmingCDF>((content) => ({
      contentId: content.id,
      contentFarmings: content.farming,
    }));
```

2022-05-30 06:40 UTC, kittipong-castcle approved these changes

2022-05-30 06:40 UTC, merged