Feature/delete page
castcle/castcle-api pull request #1281
Opened 2022-05-31 03:41 UTC by Nongeve

2022-06-01 08:29 UTC, kittipong-castcle requested changes

2022-06-01 08:29 UTC, kittipong-castcle commented on libs/database/src/lib/database.module.ts
> +    CommentServiceV2,
```suggestion
```
ซ้ำเพียบ ลบด้วย

2022-06-01 08:29 UTC, kittipong-castcle commented on libs/database/src/lib/services/user.service.v2.ts
> +    });
ย้ายไปไว้ใน repo

```suggestion
    await this.repository.deleteUser({_id: page._id});
```

2022-06-01 09:29 UTC, kittipong-castcle requested changes

2022-06-01 09:29 UTC, kittipong-castcle commented on apps/users/src/app/controllers/pages.controller.v2.ts
> +    @Param('id') id: string,
```suggestion
  @Delete(':pageId')
  async deletePage(
    @Auth() {account}: Authorizer,
    @Param() {pageId}: GetPageParam,
```
เพิ่ม param validation

2022-06-01 09:29 UTC, kittipong-castcle commented on libs/database/src/lib/services/user.service.v2.ts
> +    }
1. find page
2. if !page => throw
3. if String(page.ownerAccount) !== account.id => throw
4. if !account.verifyPassword() => throw

2022-06-02 03:29 UTC, kittipong-castcle approved these changes

2022-06-02 06:34 UTC, julapong-castcle approved these changes

2022-06-02 06:37 UTC, merged