Implement register firebase token v2
castcle/castcle-api pull request #1327
Opened 2022-06-07 16:22 UTC by nucastcle

2022-06-08 10:45 UTC, kittipong-castcle requested changes

2022-06-08 10:45 UTC, kittipong-castcle commented on apps/authentications/src/app/controllers/authentications.controller.v2.ts
> +    this.authenticationService.createAccountDevice(body, account);
```suggestion
    await this.authenticationService.createAccountDevice(body, account);
```

2022-06-08 10:45 UTC, kittipong-castcle commented on apps/authentications/src/app/controllers/authentications.controller.v2.ts
> +    this.authenticationService.deleteAccountDevice(body, account);
```suggestion
    await this.authenticationService.deleteAccountDevice(body, account);
```

2022-06-08 10:45 UTC, kittipong-castcle commented on libs/database/src/lib/services/authentication.service.v2.ts
> +    const devices = account?.devices?.find(
```suggestion
    const device = account.devices?.find(
```
account is required

2022-06-08 10:45 UTC, kittipong-castcle commented on apps/authentications/src/app/controllers/authentications.controller.v2.ts
> +  @Delete('register/notification')
```suggestion
  @Delete('register/notification')
  @HttpCode(HttpStatus.NO_CONTENT)
```

2022-06-08 10:45 UTC, kittipong-castcle commented on libs/database/src/lib/services/authentication.service.v2.ts
> +    }
```suggestion
    if (device) device.firebaseToken = body.firebaseToken;
    else (account.devices ||= []).push({
              uuid: body.uuid,
              platform: body.platform,
              firebaseToken: body.firebaseToken,
            })
            
            account.markModified('devices');
            await account.save();
```

2022-06-09 03:21 UTC, kittipong-castcle approved these changes

2022-06-09 03:54 UTC, julapong-castcle approved these changes

2022-06-09 03:54 UTC, merged