Feature/metadata-v2
castcle/castcle-api pull request #1332
Opened 2022-06-08 08:53 UTC by Nongeve

2022-06-14 06:46 UTC, kittipong-castcle requested changes

2022-06-14 06:46 UTC, kittipong-castcle commented on libs/database/src/lib/services/metadata.service.v2.ts
> +  constructor(private repositoryService: Repository) {}
```suggestion
  constructor(private repository: Repository) {}
```

2022-06-14 09:14 UTC, nucastcle approved these changes

2022-06-15 06:18 UTC, julapong-castcle approved these changes

2022-06-15 06:36 UTC, kittipong-castcle approved these changes

2022-06-15 08:10 UTC, merged