Improve reporting add on db
castcle/castcle-api pull request #1346
Opened 2022-06-13 04:34 UTC by nucastcle

2022-06-13 10:24 UTC, julapong-castcle approved these changes

2022-06-14 06:40 UTC, kittipong-castcle requested changes

2022-06-14 08:27 UTC, Nongeve approved these changes

2022-06-15 06:44 UTC, kittipong-castcle requested changes

2022-06-15 06:44 UTC, kittipong-castcle commented on libs/database/src/lib/schemas/reporting.schema.ts
> +  reported: User | Content;
```suggestion
  payload: User | Content;
```
น่าจะดู make sense กว่านะ ระหว่าง `reporting.payload` กับ `reporting.reported`

2022-06-15 06:44 UTC, kittipong-castcle commented on libs/database/src/lib/schemas/reporting.schema.ts
> +  reportedBy?: Types.ObjectId;
```suggestion
  by?: Types.ObjectId;
```

2022-06-15 11:36 UTC, merged