Improve accept pdpa
castcle/castcle-api pull request #1353
Opened 2022-06-14 09:05 UTC by nucastcle

2022-06-14 10:04 UTC, kittipong-castcle requested changes

2022-06-14 10:04 UTC, kittipong-castcle commented on libs/database/src/lib/services/authentication.service.v2.ts
> +    const datePDPA = Environment.PDPA_ACCEPT_DATES;
```suggestion
    if (Environment.PDPA_ACCEPT_DATES.length) {
      (account.pdpa ??= {})[Environment.PDPA_ACCEPT_DATES[0]] = true;
    }
```

ควรจะเซ็ท accept แค่ตัวล่าสุดนะครับ

2022-06-14 10:04 UTC, kittipong-castcle commented on libs/database/src/lib/services/user.service.v2.spec.ts
> +      Environment.PDPA_ACCEPT_DATES = ['20200601', '20200701'];
```suggestion
      Environment.PDPA_ACCEPT_DATES = ['20200701', '20200601'];
```
sort (desc) ด้วยครับ

2022-06-14 10:04 UTC, kittipong-castcle commented on libs/database/src/lib/services/user.service.v2.spec.ts
> +      expect(userResponse).toBeTruthy();
```suggestion
      expect(userResponse.pdpa).toBeTruthy();
```

2022-06-14 10:04 UTC, kittipong-castcle commented on libs/database/src/lib/services/user.service.v2.spec.ts
> +      expect(userResponse).toBeTruthy();
```suggestion
      expect(userResponse.pdpa).toBeTruthy();
```

2022-06-14 10:04 UTC, kittipong-castcle commented on libs/database/src/lib/services/user.service.v2.ts
> +      throw CastcleException.INVALID_DATE;
```suggestion
```
validate ใน dto ได้ไหม ลองใช้พวก `@IsIn` ไรพวกนั้น

2022-06-14 10:04 UTC, kittipong-castcle commented on libs/database/src/lib/services/user.service.v2.ts
> +    return user.toUserResponseV2();
```suggestion
    return user.toOwnerResponse();
```

2022-06-14 10:04 UTC, kittipong-castcle commented on libs/database/src/lib/services/user.service.v2.ts
> +      : (account.pdpa = { [date]: true });
```suggestion
    (account.pdpa ??= {})[date] = true;
```

2022-06-14 10:05 UTC, kittipong-castcle requested changes

2022-06-15 04:43 UTC, kittipong-castcle approved these changes

2022-06-15 06:19 UTC, julapong-castcle approved these changes

2022-06-15 06:19 UTC, merged