Import backoffice
castcle/castcle-api pull request #1361
Opened 2022-06-17 05:08 UTC by Nongeve

2022-06-17 07:15 UTC, julapong-castcle requested changes

2022-06-17 07:15 UTC, julapong-castcle commented on apps/backoffices/src/app/config/config.ts
> +];
ใช้ lib กลางแทนได้ไหม ??

2022-06-17 07:15 UTC, julapong-castcle commented on apps/backoffices/src/app/app.module.ts
> +  environment.DB_DATABASE_NAME_BACKOFFICE,
env ที่เพิ่มมาใหม่ให้ไปใส่ที่ .env.example ด้วย

2022-06-17 07:15 UTC, julapong-castcle commented on apps/backoffices/src/app/app.module.ts
> +      connectionName: environment.DB_DATABASE_NAME_BACKOFFICE,
env ที่เพิ่มมาใหม่ให้ไปใส่ที่ .env.example ด้วย

2022-06-17 07:15 UTC, julapong-castcle commented on apps/backoffices/src/environments/environment.ts
> +};
ใช้แบบนี้เฉยๆ ได้ไหม ??

```
export const environment = {
  production: false,
};
```

2022-06-17 07:15 UTC, julapong-castcle commented on libs/environments/src/lib/environments.ts
> +  static DB_DATABASE_NAME = process.env.DB_DATABASE_NAME || '';
ทำไมต้องเปลี่ยนเป็น public?

2022-06-17 07:21 UTC, kittipong-castcle requested changes

2022-06-19 07:41 UTC, julapong-castcle requested changes

2022-06-19 07:41 UTC, julapong-castcle commented on .env.example
> +CLOUDFRONT_PRIVATE_KEY=
ใช้ prefix นำหน้าเป็น BACKOFFICE_???_???

2022-06-20 07:00 UTC, closed without merging