manage staff api backoffice
castcle/castcle-api pull request #1379
Opened 2022-06-22 07:06 UTC by Nongeve

2022-06-23 15:12 UTC, julapong-castcle approved these changes

2022-06-27 07:08 UTC, kittipong-castcle requested changes

2022-06-27 07:08 UTC, kittipong-castcle commented on apps/backoffices/src/app/guards/role.guard.spec.ts
> +    return;
?

2022-06-27 07:08 UTC, kittipong-castcle commented on apps/backoffices/src/app/guards/role.guard.ts
> +export const Roles = (roles: RoleStaff[]) => SetMetadata('roles', roles);
```suggestion
export const RequiredPermissions = (...permissions: Permission[]) => SetMetadata('permission', permissions);
```

ปล. ใช้ `...` จะได้เรียก `@RequiredPermissions(A, B, C)` ได้เลย ไม่ต้องใส่ []

2022-06-27 07:08 UTC, kittipong-castcle commented on apps/backoffices/src/app/interceptors/credential.interceptor.ts
> +export class CredentialInterceptor implements NestInterceptor {
ควรอยู่ใน guard

2022-06-27 07:08 UTC, kittipong-castcle commented on apps/backoffices/src/app/controllers/authentication.controller.ts
> +  @Roles([RoleStaff.ADMINISTRATOR])
ใช้เป็น Attribute based ดีกว่านะ ไม่ก็ลองดูพวก nestjs passport

2022-06-28 13:48 UTC, nucastcle commented on apps/backoffices/src/app/app.module.ts
>      }),
ทำ mogoose module backoffice ไว้ใน libs/environments/src/lib/factories.ts ได้ไหมครับ

2022-06-28 13:51 UTC, nucastcle commented on apps/backoffices/src/app/controllers/authentication.controller.ts
> +    const { id } = Token.decodeToken<StaffDto>(auth.replace(/Bearer\s+/, ''));
ใช้ $payload ใน request ได้ไหมครับ

2022-06-28 13:53 UTC, nucastcle commented on apps/backoffices/src/app/guards/permisson.guard.ts
> +    private stafAbility: StaffAbility,
```suggestion
    private staffAbility: StaffAbility,
```

2022-06-30 15:56 UTC, kittipong-castcle approved these changes

2022-06-30 16:17 UTC, merged