Implement and improve function all new ###### CastcleName
castcle/castcle-api pull request #1380
Opened 2022-06-23 09:45 UTC by nucastcle

2022-06-27 03:26 UTC, kittipong-castcle requested changes

2022-06-27 03:26 UTC, kittipong-castcle commented on apps/authentications/src/app/controllers/authentications.controller.v2.ts
> +    };
```suggestion
    return { suggestCastcleId };
```

2022-06-27 03:26 UTC, kittipong-castcle commented on .env.example
> +SUGGESTION_URL=
```suggestion
# Castcle ID Suggest URL
CASTCLE_ID_SUGGESTION_URL=
```
เดี๋ยวจะสับสนกับ suggest user ของ DS

2022-06-27 03:26 UTC, kittipong-castcle commented on libs/utils/commons/src/lib/configs/names/index.ts
>  export const LENGTH_MIN = 4;
```suggestion
```

เอาไปไว้ใน s3 ด้วยดิ

2022-06-27 03:26 UTC, kittipong-castcle commented on libs/environments/src/lib/environments.ts
> +  static SUGGESTION_URL = process.env.SUGGESTION_URL;
```suggestion
  static CASTCLE_ID_SUGGESTION_URL = process.env. CASTCLE_ID_SUGGESTION_URL;
```

2022-06-27 03:45 UTC, PopCastcle commented on libs/database/src/lib/services/authentication.service.v2.spec.ts
> +      expect(suggestId).not.toEqual(loginResponse.profile.castcleId);
Will it has another cast that's not return the same thing?

2022-06-27 06:57 UTC, kittipong-castcle requested changes

2022-06-27 06:57 UTC, kittipong-castcle commented on libs/utils/commons/src/lib/castcle-name.ts
>  export class CastcleName {
```suggestion
export class CastcleName {
  static toStug(keyword: string): string;
}
```
นอกนั้นย้ายไปไว้ใน repository

2022-06-27 06:57 UTC, kittipong-castcle commented on libs/utils/commons/src/index.ts
> +export * from './lib/castcle-request';
```suggestion
```

2022-06-27 06:57 UTC, kittipong-castcle commented on libs/database/src/lib/services/user.service.v2.ts
>      if (pageIsExist) throw new CastcleException('PAGE_IS_EXIST');
```suggestion
   const availableCastcleId = await this.repository.suggestCastcleId(dto.castcleId)
```

2022-06-27 06:57 UTC, kittipong-castcle commented on libs/database/src/lib/repositories/index.ts
> +  async getUserAvailable(suggestCastcleId: string) {
```suggestion
  async suggestCastcleId(...preferKeywords: string[]) {
```
ควรรับพวก keyword ที่อยากตั้ง เช่น preferCastcleId, firstName, lastName, socialName อะไรแบบนี้

ถ้ามี any keyword ก็เอามาตั้ง ถ้าซ้ำก็เติมเลข (number)
ถ้าไม่มี ก็ค่อยไปเอาพวก keywords จาก s3 (+number ถ้าซ้ำ)

ปล. ไม่อยากให้ใช้ `Date.now()` เพราะมันมีโอกาสที่มีคนตั้งล่วงหน้าไว้ แล้วมันไปซ้ำ

2022-06-27 06:57 UTC, kittipong-castcle commented on libs/database/src/lib/services/authentication.service.v2.ts
> +  async suggestCastcleId(name: string) {
```suggestion
  async suggestCastcleId(...preferKeywords: string[]) {
    return this.repository.suggestCastcleId(...preferKeywords)
  }
```

2022-06-29 07:39 UTC, kittipong-castcle requested changes

2022-06-29 07:39 UTC, kittipong-castcle commented on libs/database/src/lib/models/user.model.ts
> +}
```suggestion
export interface CastcleIdMetadata {
  minLength: number;
  maxLength: number;
  bannedWords: string[];
  nouns: string[];
  adjectives: string[];
}
```
รวมพวกคำที่ใช้ไม่ได้มาอยู่ใน bannedWords เลย

2022-06-29 07:39 UTC, kittipong-castcle commented on libs/utils/commons/src/lib/castcle-name.ts
> +    return keyword?.toLowerCase().replace(/\s|\W/g, '');
```suggestion
    return keyword?.toLowerCase().replace(/\W/g, '_');
```

1. `\s` = whitespace, tab, new line ส่วน `\W` = not A-Z,a-Z,0-9,_  ดังนั้นถ้าจะใช้ \W ก็ไม่ต้องมี \s ก็ได้ครับ
2. อยากให้ replace ด้วย _ ไม่งั้นสมมติ `james&luton` จะกลางเป็น `jamesluton` แล้วถ้า banned words มี slut อยู่ มันจะเจอเป็นคำหยาบ

2022-06-29 07:39 UTC, kittipong-castcle commented on libs/database/src/lib/services/user.service.v2.spec.ts
>      it('should return error when castcleId exist', async () => {
```suggestion
    it('should return error? when castcleId exist', async () => {
```
ใน test ไม่เห็นมี throw error เลยครับ เปลี่ยนให้สอดคล้องด้วยครับ

2022-06-29 07:39 UTC, kittipong-castcle commented on libs/database/src/lib/repositories/index.ts
> +  }
```suggestion
  async suggestCastcleId(preferredCastcleId?: string) {
    if (!this.castcleIdMetadata) {
      const castcleIdMetadata = await CastcleName.getSuggestWords(
        Environment.CASTCLE_ID_SUGGESTION_URL,
      );
      
      if (!castcleIdMetadata) throw Error(...)
      this.castcleIdMetadata = castcleIdMetadata;
    };
    
    const castcleId =
      this.isValidSuggestWord(preferredCastcleId)
        ? CastcleName.toStug(castcleId)
        : this.randomCastcleId();

    const [availableId] =
      await this.userModel.aggregate<GetAvailableIdResponse>(
        pipelineOfGetAvailableId(castcleId),
      );

    return `${castcleId}${availableId ? availableId?.number : ''}`;
```

2022-06-29 07:39 UTC, kittipong-castcle commented on libs/database/src/lib/repositories/index.ts
> +  private preferCastcleId({ SUBJECTS, ADJECTIVES }: SuggestionWords) {
```suggestion
  private randomCastcleId() {
```

2022-06-29 07:39 UTC, kittipong-castcle commented on libs/database/src/lib/repositories/index.ts
> +    }`;
```suggestion
    return `${this.castcleIdMetadata.adjectives[randomLength(SUBJECTS.length)]}${
      this.castcleIdMetadata.nouns[randomLength(ADJECTIVES.length)]
    }`;
```

2022-06-29 07:39 UTC, kittipong-castcle commented on libs/database/src/lib/repositories/index.ts
> +  private isValidSuggestWord(inputName: string, suggestWords: SuggestionWords) {
```suggestion
  private isValidCastcleId(castcleId: string) {
```

2022-06-29 07:39 UTC, kittipong-castcle commented on libs/database/src/lib/repositories/index.ts
> +  }
```suggestion
    if (!suggestWords) return false;

    const hasBannedWord =
      this.castcleIdMetadata.bannedWords.some(bannedWord=>Regex(bannedWord,'i').test(castcleId));

    return (
      !hasBannedWord &&
      inputName.length >= suggestWords.LENGTH_MIN &&
      inputName.length <= suggestWords.LENGTH_MAX
    )
  }
```

2022-06-29 07:40 UTC, kittipong-castcle commented on libs/database/src/lib/repositories/index.ts
> +  }
```
    const patternSpecial = /[`!@#$%^&*()_+\-=\[\]{};':"\\|,.<>\/?~]/;
```
ไม่ควรจะมีพวก special char แล้ว เพราะถูก replace ตอน convert to slug แล้ว

2022-06-30 15:40 UTC, julapong-castcle approved these changes

2022-07-01 05:14 UTC, bxneter approved these changes

2022-07-01 07:21 UTC, merged