Implement metadata reporting
castcle/castcle-api pull request #1385
Opened 2022-06-23 17:46 UTC by nucastcle

2022-06-27 04:26 UTC, julapong-castcle approved these changes

2022-06-27 07:17 UTC, kittipong-castcle requested changes

2022-06-27 07:17 UTC, kittipong-castcle commented on libs/database/src/lib/services/metadata.service.v2.ts
> +      },
```suggestion
      { sort: { order: 1 } },
```

prefer single line

2022-06-27 07:17 UTC, kittipong-castcle commented on libs/database/src/lib/services/metadata.service.v2.spec.ts
> +    await new (service as any).repository.reportingSubjectModel({
```suggestion
    service = moduleRef.get(MetadataServiceV2);
    reportingSubjectModel = moduleRef.get(getModelToken('ReportingSubject'))

    await new reportingSubjectModel({
```

2022-06-27 07:17 UTC, kittipong-castcle commented on libs/database/src/lib/services/metadata.service.v2.spec.ts
> +      const reportSubjects = await (service as any).getReportSubjects();
```suggestion
      const reportSubjects = await service.getReportSubjects();
```

2022-06-27 07:17 UTC, kittipong-castcle commented on libs/database/src/lib/schemas/reporting-subject.schema.ts
> +export class ReportingSubjectDocument extends Document {
ไม่เอาไปรวมกับ reporting อะ เพิ่มเป็น type: metadata ก็ได้นะ payload มันก็เป็น any อยู่แล้ว

2022-06-27 07:17 UTC, kittipong-castcle commented on libs/database/src/lib/repositories/index.ts
>    private getUserQuery(filter: UserQuery) {
```suggestion

  private getUserQuery(filter: UserQuery) {
```
อยากให้มี new line ระหว่าง function+function, class+class, import+class + ก่อน import พอมันติดกันหมด มันอ่านยากครับ.

2022-06-28 03:26 UTC, kittipong-castcle approved these changes

2022-06-28 03:50 UTC, merged