Improve reporting
castcle/castcle-api pull request #1398
Opened 2022-06-28 13:33 UTC by nucastcle

2022-06-30 15:41 UTC, julapong-castcle approved these changes

2022-07-01 03:16 UTC, Nongeve approved these changes

2022-07-01 05:35 UTC, bxneter requested changes

2022-07-01 05:35 UTC, bxneter commented on libs/database/src/lib/models/metadata.model.ts
> +export enum MetadataType {
Move this to `metadata.enum.ts`

2022-07-01 05:35 UTC, bxneter commented on libs/database/src/lib/schemas/metadata.schema.ts
> +MetadataSchema.methods.toMetadataPayload = function () {
ใช้ metadata.payload แทนไหมครับ ?

```suggestion
```

2022-07-01 05:35 UTC, bxneter commented on libs/database/src/lib/services/country.service.ts
> +        'payload.dialCode': dialCode,
```suggestion
        type: MetadataType.COUNTRY,
        'payload.dialCode': dialCode,
```

2022-07-01 05:35 UTC, bxneter commented on libs/database/src/lib/services/country.service.ts
> +    return metadata.toMetadataPayload();
```suggestion
    return metadata.payload;
```

2022-07-01 05:35 UTC, bxneter commented on libs/database/src/lib/services/language.service.ts
> +/** @deprecated */
```suggestion
```

2022-07-01 05:35 UTC, bxneter commented on libs/database/src/lib/services/language.service.ts
> +  constructor(@InjectModel('Metadata') public metadataModel: Model<Metadata>) {}
```suggestion
  constructor(@InjectModel('Metadata') public metadataModel: Model<Metadata<Language>>) {}
```

2022-07-01 05:35 UTC, bxneter commented on libs/database/src/lib/dtos/reporting.dto.v2.ts
> +export class ReportingDtoV2 {
```suggestion
class ReportingDtoV2 {
  message;
  subject;
}

export class ReportContentDto extends ReportingDtoV2 { ... }
export class ReportUserDto extends ReportingDtoV2 { ... }
```

2022-07-01 05:35 UTC, bxneter commented on libs/database/src/lib/services/language.service.ts
>    create = async (language: LanguagePayloadDto) => {
ลบออกครับ มันใช้แค่ใน tests

2022-07-01 05:35 UTC, bxneter commented on libs/database/src/lib/schemas/metadata.schema.ts
> +class MetadataDocument extends CastcleBase {
```suggestion
class Metadata<T extends Country | Language> extends CastcleBase {
  ...
  
  payload: T
}
```

2022-07-01 09:33 UTC, kittipong-castcle approved these changes

2022-07-01 10:16 UTC, kittipong-castcle requested changes

2022-07-01 10:16 UTC, kittipong-castcle commented on apps/feeds/src/app/controllers/country.controller.ts
>    constructor(private countryService: CountryService) {}
```suggestion
  constructor(private metadataService: MetadataService) {}
```

use a new metadataService and remove unused country+language services

2022-07-01 10:16 UTC, kittipong-castcle commented on libs/database/src/lib/schemas/language.schema.ts
> +export class Language extends CastcleBase {
Remove all `@Prop()` and `@Schema` from mongoose.
Use plain class and move this class to `language.model.ts`.
Remove unused `LanguageSchema`

- Country
- Language
- ReportingSubject

2022-07-01 10:16 UTC, kittipong-castcle commented on libs/database/src/lib/repositories/index.ts
> +      Metadata<Country | Language | ReportingSubject>
```suggestion
      Metadata<any>
```

2022-07-01 10:16 UTC, kittipong-castcle commented on libs/database/src/lib/repositories/index.ts
> +  findMetadatas(filter?: MatadataQuery, queryOptions?: QueryOptions) {
```suggestion
  findMetadatas<T extends ... | ... | ...>(filter?: MatadataQuery, queryOptions?: QueryOptions): Promise<Metadata<T>[]> {
```

2022-07-01 10:16 UTC, kittipong-castcle commented on libs/database/src/lib/services/metadata.service.v2.ts
> +      .findMetadatas({ type: MetadataType.LANGUAGE })
```suggestion
      .findMetadatas<Language>({ type: MetadataType.LANGUAGE })
```

2022-07-01 10:16 UTC, kittipong-castcle commented on libs/database/src/lib/services/metadata.service.v2.ts
> +      .findMetadatas({ type: MetadataType.COUNTRY }, { sort: sortBy })
```suggestion
      .findMetadatas<Country>({ type: MetadataType.COUNTRY }, { sort: sortBy })
```

2022-07-01 10:16 UTC, kittipong-castcle commented on libs/database/src/lib/services/metadata.service.v2.ts
> +      .findMetadatas(
```suggestion
      .findMetadatas<ReportingSubject>(
```

2022-07-03 04:58 UTC, merged