Improve new cache key
castcle/castcle-api pull request #1428
Opened 2022-07-04 10:05 UTC by nucastcle

2022-07-04 10:50 UTC, julapong-castcle approved these changes

2022-07-04 10:53 UTC, kittipong-castcle requested changes

2022-07-04 10:53 UTC, kittipong-castcle commented on libs/utils/interceptors/src/lib/cache/http.cache.individual.interceptor.ts
> +      const finalKey = `${cacheKey}-${token}-${request.raw['originalUrl']}`;
request.raw.originalUrl ไม่น่าจะมีใน fastify นะ และถ้ามีการเพิ่มลด query มา ก็จะได้ข้อมูลเก่าออกไป ควรจะใช้
- cacheKey
- token
- request.url
- JSON.stringify(request.query)

2022-07-05 02:59 UTC, kittipong-castcle approved these changes

2022-07-05 05:46 UTC, merged