Feature/noti readall
castcle/castcle-api pull request #155
Opened 2021-09-12 02:55 UTC by zong09

2021-09-13 04:13 UTC, watit-castcle approved these changes

2021-09-13 10:57 UTC, PopCastcle approved these changes

2021-09-13 11:01 UTC, julapong-castcle requested changes

2021-09-13 11:01 UTC, julapong-castcle commented on libs/database/src/lib/dtos/notification.dto.ts
> +// }
comment เพื่อจะใช้ต่อหรือยังไงครับ
ถ้าไม่ใช้งาน code แล้ว ลบออกเลยครับ

2021-09-13 11:07 UTC, zong09 commented on libs/database/src/lib/dtos/notification.dto.ts
> +// }
ขอโทษทีคับลืมลบ 
แก้ไขแล้วคับ

2021-09-16 03:30 UTC, julapong-castcle approved these changes

2021-09-16 04:02 UTC, merged