Feature/consumer queue
castcle/castcle-api pull request #174
Opened 2021-09-18 03:30 UTC by zong09

2021-09-19 05:42 UTC, julapong-castcle requested changes

2021-09-19 05:42 UTC, julapong-castcle commented on .env.example
> +PRIVATE_KEY = "Secret String"
รบกวนเพิ่ม prefix หน่อยครับ เผื่อชื่อซ้ำครับ
```
FIREBASE_PROJECT_ID
FIREBASE_CLIENT_EMAIL
FIREBASE_ PRIVATE_KEY
```

2021-09-19 05:42 UTC, julapong-castcle commented on libs/environments/src/lib/environments.ts
> +  firebase_private_key: process.env.PRIVATE_KEY
process.env ก็แก้ตามด้านบนครับ

2021-09-19 08:34 UTC, zong09 commented on .env.example
> +PRIVATE_KEY = "Secret String"
แก้แล้วคับ

2021-09-19 08:34 UTC, zong09 commented on libs/environments/src/lib/environments.ts
> +  firebase_private_key: process.env.PRIVATE_KEY
แก้แล้วคับ

2021-09-19 09:33 UTC, julapong-castcle approved these changes

2021-09-19 10:12 UTC, watit-castcle approved these changes

2021-09-20 04:51 UTC, PopCastcle approved these changes

2021-09-20 04:52 UTC, merged