Feature/authentications/request otp
castcle/castcle-api pull request #288
Opened 2021-10-13 13:33 UTC by PorscheTanut

api /authentications
  - POST: /forgotPasswordRequestOTP
  - POST: /forgotPasswordVerificationOTP
  - POST: /requestOTP
  - POST: /verificationOTP

2021-10-13 14:07 UTC, julapong-castcle commented on .env.example
>  FB_CLIENT_SECRET = "Secret String"
FB_CLIENT_SECRET บรรทัดที่ 72 กับ 78 ซ้ำกันครับ

2021-10-14 02:55 UTC, zong09 requested changes

2021-10-14 02:55 UTC, zong09 commented on libs/database/src/lib/services/authentication.service.ts
> +  async resetPassword(refCode: string, newPassword: string) {
เพิ่ม unit test function ใหม่ด้วยคับ

2021-10-15 07:14 UTC, PorscheTanut commented on libs/database/src/lib/services/authentication.service.ts
> +  async resetPassword(refCode: string, newPassword: string) {
เพิ่มเรียบร้อยครับ

2021-10-17 11:27 UTC, closed without merging