Add common token class
castcle/castcle-api pull request #36
Opened 2021-07-30 03:26 UTC by TanasinV

2021-07-30 07:28 UTC, PopCastcle commented on libs/token/src/lib/token.ts
> +    }
payload ต้องเพิ่มประเภท(สำหรับ verifiyEmailPayload) หรือเป็น map  หรือ any ไปก่อนครับ

2021-07-30 07:46 UTC, PopCastcle commented on libs/token/src/lib/token.ts
> +  validateToken(token: string, type: TokenType): any {
อันนี้ไม่แน่ใจว่า payload ต้องเป็น jwt.JwtPayload  รึป่าวครับ

2021-07-30 08:11 UTC, TanasinV commented on libs/token/src/lib/token.ts
> +  validateToken(token: string, type: TokenType): any {
ใช่ครับ เป็น jwt.JwtPayload ครับ

2021-07-30 10:12 UTC, julapong-castcle requested changes

2021-07-30 10:12 UTC, julapong-castcle commented on libs/token/jest.config.js
> +module.exports = {
เพิ่ม header license ด้วยครับ

2021-07-30 10:12 UTC, julapong-castcle commented on libs/token/src/index.ts
> +export * from './lib/token';
เพิ่ม header license ด้วยครับ

2021-07-30 10:12 UTC, julapong-castcle commented on package.json
> +    "chokidar": "^3.5.2",
libs นี้ไม่ได้ใช้ หรือเปล่าครับ ลบออกด้วยครับ

2021-07-30 10:12 UTC, julapong-castcle commented on package.json
> +    "watchpack": "^1.7.5",
libs นี้ไม่ได้ใช้ หรือเปล่าครับ ลบออกด้วยครับ

2021-07-30 10:12 UTC, julapong-castcle commented on package.json
> +    "watchpack-chokidar2": "^2.0.1"
libs นี้ไม่ได้ใช้ หรือเปล่าครับ ลบออกด้วยครับ

2021-07-31 12:40 UTC, PopCastcle commented on libs/database/src/lib/services/account.service.spec.ts
> +      });
ไฟล์นี้ ไม่น่าจะได้ใช้นะครับ

2021-07-31 12:41 UTC, PopCastcle commented on libs/database/src/lib/services/account.service.ts
> +      createDate: new Date(),
ไฟล์นี้ไม่น่าจะได้ใช้นะครับ

2021-08-01 18:36 UTC, TanasinV commented on libs/token/src/lib/token.ts
> +    }
เพิ่ม interface ให้ละครับ

2021-08-01 18:36 UTC, TanasinV commented on libs/database/src/lib/services/account.service.spec.ts
> +      });
ลบออกละครับ

2021-08-01 18:36 UTC, TanasinV commented on libs/database/src/lib/services/account.service.ts
> +      createDate: new Date(),
ลบออกละครับ

2021-08-04 07:27 UTC, closed without merging