Feature/request opt
castcle/castcle-api pull request #395
Opened 2021-11-04 11:04 UTC by zong09

Fix Bug :  [GET] /metadata/country
Feature : 📝 [POST] /authentications/forgotPasswordRequestOTP

2021-11-05 08:34 UTC, PopCastcle commented on apps/authentications/src/app/app.service.ts
> +    credentiial: CredentialRequest
Typo

2021-11-05 08:35 UTC, PopCastcle requested changes
Has some typo

2021-11-05 08:59 UTC, zong09 commented on apps/authentications/src/app/app.service.ts
> +    credentiial: CredentialRequest
fixed

2021-11-05 10:05 UTC, PopCastcle approved these changes

2021-11-06 01:41 UTC, julapong-castcle approved these changes

2021-11-06 04:01 UTC, merged