Feature/reset password otp
castcle/castcle-api pull request #412
Opened 2021-11-11 02:53 UTC by zong09

2021-11-11 12:29 UTC, julapong-castcle approved these changes

2021-11-12 03:23 UTC, PopCastcle commented on apps/authentications/src/app/app.controller.ts
> +  @Post('resetPasswordSubmit')
Please use Castcle Decoration krub

2021-11-12 03:25 UTC, PopCastcle requested changes
Please use Castcle Decorator

2021-11-12 09:35 UTC, zong09 commented on apps/authentications/src/app/app.controller.ts
> +  @Post('resetPasswordSubmit')
fixed

2021-11-15 06:50 UTC, PopCastcle approved these changes

2021-11-15 06:54 UTC, merged