Update schema of SyncAccounts
castcle/castcle-api pull request #481
Opened 2021-11-26 07:45 UTC by kittipong-castcle

2021-11-26 09:46 UTC, PopCastcle approved these changes

2021-11-27 02:51 UTC, zong09 approved these changes

2021-11-29 04:23 UTC, julapong-castcle approved these changes

2021-12-01 05:26 UTC, julapong-castcle approved these changes

2021-12-01 10:38 UTC, zong09 requested changes

2021-12-01 10:38 UTC, zong09 commented on libs/database/src/lib/database.module.ts
> +import { SocialSyncSchema } from './schemas/social-sync.schema';
file name น่าจะเป็น socialSync.schema

2021-12-01 10:38 UTC, zong09 commented on libs/database/src/lib/services/social-sync.service.ts
> +import { Injectable } from '@nestjs/common';
file name เหมือนกันน่าจะเป็น socialSync.service.ts

2021-12-01 11:00 UTC, kittipong-castcle commented on libs/database/src/lib/database.module.ts
> +import { SocialSyncSchema } from './schemas/social-sync.schema';
ผมอัพเดท file name casing เป็น `pascal-case` ครับ

2021-12-01 14:54 UTC, zong09 approved these changes

2021-12-02 04:01 UTC, PopCastcle approved these changes

2021-12-02 04:02 UTC, merged