Add Youtube webhook handler
castcle/castcle-api pull request #482
Opened 2021-11-26 09:27 UTC by kittipong-castcle

2021-11-26 09:49 UTC, PopCastcle approved these changes

2021-11-27 02:50 UTC, zong09 approved these changes

2021-11-29 04:22 UTC, julapong-castcle approved these changes

2021-12-01 10:40 UTC, zong09 requested changes

2021-12-01 10:40 UTC, zong09 commented on libs/database/src/lib/services/social-sync.service.ts
> +
filename น่าจะเป็น socialSync.service.ts

2021-12-01 14:55 UTC, zong09 approved these changes

2021-12-02 04:00 UTC, PopCastcle approved these changes

2021-12-02 04:01 UTC, merged