Add block/unblock user API
castcle/castcle-api pull request #503
Opened 2021-12-02 09:55 UTC by kittipong-castcle

2021-12-02 13:06 UTC, julapong-castcle approved these changes

2021-12-02 15:20 UTC, PopCastcle commented on libs/database/src/lib/services/user.service.ts
> +    const initialRelationship = {
shouldn't it be blocking relationship?

2021-12-02 15:23 UTC, PopCastcle commented on libs/database/src/lib/services/user.service.ts
> +    if (!unblockUser) throw CastcleException.USER_OR_PAGE_NOT_FOUND;
Make sure when throw exception has not effect with unit test

2021-12-02 15:23 UTC, PopCastcle requested changes
I think user.service.spec might need to add 2 functions

2021-12-03 10:21 UTC, zong09 approved these changes

2021-12-07 04:11 UTC, merged