Feature/sync social get update delete
castcle/castcle-api pull request #562
Opened 2021-12-15 12:31 UTC by zong09

- GET
- PUT
- DELETE

2021-12-17 04:18 UTC, julapong-castcle approved these changes

2021-12-21 10:54 UTC, kittipong-castcle requested changes

2021-12-21 10:54 UTC, kittipong-castcle commented on apps/users/src/app/app.controller.ts
> +  @Delete('syncSocial')
By default, `@Delete(...)` returns HTTP status 200 (OK). We should override the return status by adding `@HttpCode(HttpStatus.NO_CONTENT)`

```suggestion
  @Delete('syncSocial')
  @HttpCode(HttpStatus.NO_CONTENT)
```

2021-12-21 10:54 UTC, kittipong-castcle commented on apps/users/src/app/app.controller.ts
> +      return '';
If this API returns no content (204: NO_CONTENT), the `return` is unnecessary.

```suggestion
```

2021-12-21 10:54 UTC, kittipong-castcle commented on apps/users/src/app/app.controller.ts
> +      );
I think we should return/throw early by writing conditions in form of a guard clause. It's cleaner and easier to read.

```suggestion
    const user = await this._getUserFromIdOrCastcleId(body.castcleId, req);
    
    if (!user) throw new CastcleException(CastcleStatus.FORBIDDEN_REQUEST);
    
    await this.socialSyncService.update(body, user);
```

2021-12-21 10:54 UTC, kittipong-castcle commented on apps/users/src/app/app.controller.ts
> +      );
```suggestion
      throw new CastcleException(CastcleStatus.FORBIDDEN_REQUEST);
```

We already implemented the Exception Filter to handle the localization of error messages, so we don't need to pass language to the exception.

Is this correct? @PopCastcle

2021-12-21 10:54 UTC, kittipong-castcle commented on libs/database/src/lib/services/social-sync.service.ts
> +      this.logger.warn('Cnn not found social sync');
`Cnn` or `Can`?

2021-12-22 04:51 UTC, kittipong-castcle approved these changes

2021-12-22 10:47 UTC, merged