Feature/referee
castcle/castcle-api pull request #633
Opened 2022-01-07 07:43 UTC by zong09

2022-01-07 10:09 UTC, julapong-castcle approved these changes

2022-01-10 03:29 UTC, kittipong-castcle requested changes

2022-01-10 03:29 UTC, kittipong-castcle commented on apps/users/src/app/app.controller.ts
> +    @Query('untilId') untilId?: string
```suggestion
    @Query() { hasRelationshipExpansion, maxResult, sinceId, untilId }: FeedQuery
```

2022-01-10 03:29 UTC, kittipong-castcle commented on apps/users/src/app/app.controller.ts
> +    }
```suggestion
```

already validated in `FeedQuery`

2022-01-10 03:29 UTC, kittipong-castcle commented on libs/database/src/lib/dtos/common.dto.ts
> +}
UserField and ExpansionQuery have already moved to `feed.dto.ts`. I'm not sure that why we need to duplicate them in `common.dto.ts`.

2022-01-10 03:29 UTC, kittipong-castcle commented on libs/database/src/lib/dtos/feed.dto.ts
> +import { DEFAULT_QUERY_OPTIONS, ExpansionQuery } from './common.dto';
Merging conflict?
Moving back ExpansionQuery and UserField to `common.dto` can cause circular dependency.

2022-01-10 03:29 UTC, kittipong-castcle commented on libs/database/src/lib/services/user.service.ts
> +  };
```suggestion
```

Same but different naming?

2022-01-10 03:29 UTC, kittipong-castcle commented on libs/database/src/lib/services/user.service.ts
> +    }
```suggestion
    const result = await Promise.all(
        accountReferee?.map((x) => this.getUserFromAccountId(x.referringAccount._id) ?? []
    );
```

2022-01-11 06:56 UTC, kittipong-castcle approved these changes

2022-01-11 07:57 UTC, merged