Feature/fixed bug
castcle/castcle-api pull request #635
Opened 2022-01-09 10:01 UTC by zong09

Refactor Sync Social

2022-01-09 11:03 UTC, julapong-castcle approved these changes

2022-01-10 03:35 UTC, kittipong-castcle requested changes

2022-01-10 03:35 UTC, kittipong-castcle commented on apps/users/src/app/app.controller.ts
> +  @Get('sync_social')
For URL naming, we should use dashes (-) to separate keywords and use plural nouns for defining resources.

```suggestion
  @Get('sync-socials')
```

2022-01-11 06:57 UTC, kittipong-castcle approved these changes

2022-01-11 07:25 UTC, merged