Feature/user recast
castcle/castcle-api pull request #645
Opened 2022-01-12 10:56 UTC by zong09

[POST] users/:id/recast 
[GET] contents/:id/recasted
[POST] /users/:id/quotecast

2022-01-12 11:16 UTC, kittipong-castcle commented
Please use rebasing instead of merging.

2022-01-13 03:08 UTC, julapong-castcle approved these changes

2022-01-13 10:26 UTC, kittipong-castcle requested changes

2022-01-13 10:26 UTC, kittipong-castcle commented on apps/users/src/app/app.controller.ts
> +    const user = await this._getUserFromBody(req, id);
```suggestion
    @Auth() authorizer: Authorizer
  ) {
    authorizer.requestAccessForUser(id);
```

use this to check authority

2022-01-13 10:26 UTC, kittipong-castcle commented on apps/users/src/app/app.controller.ts
> +      user,
```suggestion
      authorizer.user,
```

2022-01-13 10:26 UTC, kittipong-castcle commented on libs/database/src/lib/services/content.service.ts
> +    if (content) {
```suggestion
    if (content) return;
```

please use guard return to reduce block scope

2022-01-13 10:26 UTC, kittipong-castcle commented on libs/database/src/lib/services/content.service.ts
> +        await engagement.remove();
Can we use `findOneAndRemove` instead?

2022-01-14 06:17 UTC, kittipong-castcle approved these changes

2022-01-14 06:34 UTC, merged