Feature/create page with social
castcle/castcle-api pull request #693
Opened 2022-01-30 13:19 UTC by zong09

2022-01-31 08:48 UTC, julapong-castcle approved these changes

2022-02-01 04:10 UTC, kittipong-castcle requested changes

2022-02-01 04:10 UTC, kittipong-castcle commented on apps/bases/src/app/controllers/pages.controller.ts
> +          }
```suggestion
          socialPage.links = { [syncBody.provider]: syncBody.link }
```

2022-02-01 04:10 UTC, kittipong-castcle commented on apps/bases/src/app/controllers/pages.controller.ts
> +  @UsePipes(new ValidationPipe({ skipMissingProperties: true }))
```suggestion
  @UsePipes(new ValidationPipe({ whitelist: true }))
```

2022-02-01 04:10 UTC, kittipong-castcle commented on libs/database/src/lib/schemas/user.schema.ts
> +        : null,
```suggestion
    socialSyncs: (this as User).profile?.socialSyncs ?? null,
```

[REF](https://medium.com/@suraneti.rod/javascript-optional-chaining-%E0%B8%84%E0%B8%B7%E0%B8%AD%E0%B8%AD%E0%B8%B0%E0%B9%84%E0%B8%A3-%E0%B9%83%E0%B8%99-es11-%E0%B8%97%E0%B8%B5%E0%B9%88%E0%B8%81%E0%B8%B3%E0%B8%A5%E0%B8%B1%E0%B8%87%E0%B8%88%E0%B8%B0%E0%B8%A1%E0%B8%B2%E0%B8%96%E0%B8%B6%E0%B8%87-b3bec898ec76)

2022-02-01 04:10 UTC, kittipong-castcle commented on libs/database/src/lib/services/user.service.ts
> +    return newPage.save();
immediately return

```suggestion
    return new this._userModel({
      ownerAccount: account._id,
      type: UserType.Page,
      displayId: socialPageDto.castcleId,
      displayName: socialPageDto.displayName,
      profile: {
        overview: socialPageDto.overview,
        images: {
          avatar: socialPageDto.avatar,
          cover: socialPageDto.cover,
        },
        socials: {
          facebook: socialPageDto.links?.facebook,
          twitter: socialPageDto.links?.twitter,
          youtube: socialPageDto.links?.youtube,
          medium: socialPageDto.links?.medium,
        },
        socialSyncs: socialPageDto.socialSyncs,
      },
    }).save();
```

2022-02-03 08:44 UTC, kittipong-castcle approved these changes

2022-02-03 10:15 UTC, merged