Refactor :: add new create page fucntion inside users module.
castcle/castcle-api pull request #790
Opened 2022-02-22 07:45 UTC by nucastcle

add new create page function inside users module.
Method: POST users/me/pages

2022-02-22 07:53 UTC, julapong-castcle requested changes

2022-02-22 07:53 UTC, julapong-castcle commented on apps/users/src/app/app.controller.ts
> +   * @deprecated The method should not be used. Please use POST users/me/pages
method นี้ คือสร้างมาใหม่เพื่อใช้เป็นหลัก ไม่ต้อง comment deprecated ครับ

2022-02-22 08:07 UTC, kittipong-castcle approved these changes

2022-02-23 02:54 UTC, nucastcle commented on apps/users/src/app/app.controller.ts
> +   * @deprecated The method should not be used. Please use POST users/me/pages
ลบเรียบร้อยครับ

2022-02-23 03:08 UTC, julapong-castcle approved these changes

2022-02-23 03:12 UTC, merged