add liking user
castcle/castcle-api pull request #807
Opened 2022-02-24 12:01 UTC by nucastcle

เพิ่ม feature liking เกี่ยวกับ แสดง user ที่ like content นั้นอยู่ มีใครบ้าง

2022-02-25 12:52 UTC, zong09 requested changes

2022-02-25 12:52 UTC, zong09 commented on libs/database/src/lib/schemas/user.schema.ts
> +
อันนี้ไปใช้ toUserResponse แทนได้ไหม มีอะไรต่างกันหรือเปล่า

2022-02-25 12:52 UTC, zong09 commented on libs/database/src/lib/services/content.service.ts
> +    if (sinceId) {
ตรงนี้ใช้    createCastcleFilter ได้เลย แบบนี้
```
query = await createCastcleFilter(query, {
      sinceId: paginationQuery?.sinceId,
      untilId: paginationQuery?.untilId,
    });
```

2022-02-25 13:14 UTC, nucastcle commented on libs/database/src/lib/schemas/user.schema.ts
> +
toUserResponse ไม่ได้ใส่ param usersField ของ wallet แต่ return field wallet มันไม่ตรงตาม API doc ครับ แล้วถ้าเข้าไปแก้ตรงนี้ กลัวจะเจอผลกระทบกับตัวอื่นครับ กรณีนี้ อนุโลมได้ใช่ไหมครับให้ wallet แต่ return field ไปด้วย แต่เป็น  empty object ครับ

2022-02-25 13:15 UTC, nucastcle commented on libs/database/src/lib/schemas/user.schema.ts
> +
"wallet": {}

2022-02-25 13:18 UTC, nucastcle commented on libs/database/src/lib/services/content.service.ts
> +    if (sinceId) {
เดี๋ยวผมแก้ไปใช้ตัวนี้ครับ

2022-02-25 13:26 UTC, zong09 requested changes

2022-02-25 13:26 UTC, zong09 commented on libs/database/src/lib/schemas/user.schema.ts
> +
เห็นใน spec return เป็น object_user ใช่ไหมไหมคับ
ถ้าแบบนั้นใช้ toUserResponse ได้เลยคับ

2022-02-25 15:19 UTC, zong09 requested changes

2022-02-25 15:19 UTC, zong09 commented on libs/database/src/lib/schemas/user.schema.ts
> +  toLikingResponse: (
ตรงนี้ต้องลบออกด้วยไหมคับ

2022-02-26 04:36 UTC, zong09 approved these changes

2022-02-27 06:42 UTC, merged