Feature : advertise list
castcle/castcle-api pull request #830
Opened 2022-03-01 08:35 UTC by nucastcle

Advertise List

2022-03-01 09:21 UTC, kittipong-castcle requested changes

2022-03-01 09:21 UTC, kittipong-castcle commented on apps/users/src/app/app.controller.ts
> +    }
ใช้ `Array.map` แทนครับ

```suggestion
    const ads = await Promise.all(
        adsCampaigns.map(adsCampaign=> this.adsService.transformAdsCampaignToAdsResponse(
            adsCampaign
        )))
```

2022-03-01 09:21 UTC, kittipong-castcle commented on libs/database/src/lib/services/ads.service.ts
> +    });
```suggestion
    const filter: FilterQuery<AdsCampaign> = createCastcleFilter({ owner: _id }, {
      sinceId,
      untilId,
    });
    
    // or
    const filter = createFilterQuery<AdsCampaign>(sinceId, untilId);
    
    filter.owner = _id;
```
avoid reassigning params (let)

2022-03-01 15:33 UTC, julapong-castcle approved these changes

2022-03-02 04:47 UTC, kittipong-castcle requested changes

2022-03-02 06:55 UTC, merged