Add module luxon , common fucntion dateOf and adsFilter query.
castcle/castcle-api pull request #843
Opened 2022-03-02 14:04 UTC by nucastcle

Add filter query date and create common function covert dateOf ... .

2022-03-03 11:06 UTC, kittipong-castcle requested changes

2022-03-03 11:06 UTC, kittipong-castcle commented on libs/database/src/lib/dtos/ads.dto.ts
> +export class adsQuery extends PaginationQuery {
```suggestion
export class AdsQuery extends PaginationQuery {
```

ชื่อ class/type ใช้ `PascalCase` ส่วน `camelCase` เอาไว้พวก variables

2022-03-03 13:23 UTC, zong09 approved these changes

2022-03-04 03:44 UTC, kittipong-castcle requested changes

2022-03-04 03:44 UTC, kittipong-castcle commented on libs/database/src/lib/dtos/ads.dto.ts
> +  filter: AdsFilter;
```suggestion
  filter?: AdsFilter;
```

2022-03-04 03:44 UTC, kittipong-castcle commented on libs/database/src/lib/models/ads.enum.ts
> +export enum AdsFilter {
เปลี่ยนชื่อเป็น FilterInterval หรือที่สื่อกว่านี้ครับ

2022-03-04 03:44 UTC, kittipong-castcle commented on libs/database/src/lib/dtos/ads.dto.ts
> +  timezone: string;
```suggestion
  timezone = '$timezone'
```

2022-03-04 03:44 UTC, kittipong-castcle commented on libs/utils/commons/src/lib/datetime.ts
> +export const ConvertDate = {
ทำเป็น base date ของโปรเจคนี้เลยครับ

2022-03-05 05:23 UTC, merged